### PR TITLE
[inetstack] Bug Fix: Simultaneous close misses FIN resend

### LINKED ISSUE #1529: Test tcp-bad-close is non-deterministic on catnap/windows
## Description

The tcp-bad-close test is non-deterministic on catnap/windows.

## How to Reproduce

1. Submit PR test run
2. Repeat # 1 until failure is encountered.

## Screenshots

See [this test run](https://github.com/microsoft/demikernel/actions/runs/14391164945/attempts/1) for an example.

## Expected Behavior

Determinism

### PR DESCRIPTION
**Pull request by iyzhang**
This PR closes #1529 and #1537

### CODE REVIEW

File: src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs [hunk 1]
```diff
@@ -505,40 +534,42 @@ impl Receiver {
...
-            match cb.state {
-                State::Established | State::FinWait1 | State::FinWait2 => {
-                    debug_assert_eq!(seg_len, data.len() as u32);
-                    cb.receiver.store_out_of_order_segment(seg_start, seg_end, data);
-                    // Sending an ACK here is only a "MAY" according to the RFCs, but helpful for fast retransmit.
-                    trace!("process_data(): send ack on out-of-order segment");
-                    Sender::send_ack(cb, layer3_endpoint);
-                },
-                state => warn!("Ignoring data received after FIN (in state {:?}).", state),
+        if data.len() > 0 {
```
Comment (anandbonde) [inline src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs]: We should return early by flipping the condition. This will reduce the level of nesting in this function as well.

File: src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs [hunk 2]
```diff
@@ -274,60 +186,166 @@ impl Receiver {
...
 
-        let has_data: bool = if data.len() > 0 {
-            Self::process_data(cb, layer3_endpoint, data, seg_start, seg_end, seg_len)?;
-            true
-        } else {
-            false
-        };
+        // Store whether the packet has data here because processing it will consume the DemiBuffer.
+        let has_data: bool = data.len() > 0;
+        Self::process_data_if_any(cb, layer3_endpoint, data, seg_start, seg_end, seg_len)?;
```
Comment (anandbonde) [inline src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs]: Can this call be avoided by checking `has_data` above?

File: src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs [hunk 3]
```diff
@@ -274,60 +186,166 @@ impl Receiver {
...
+    // This function causes a EOF to be returned to the user. We also know that there will be no more incoming
+    // data after this sequence number.
+    fn check_and_process_fin(
+        cb: &mut ControlBlock,
+        header: &TcpHeader,
+        seg_end: SeqNumber,
+        layer3_endpoint: &mut SharedLayer3Endpoint,
+        now: Instant,
+    ) -> Result<(), Fail> {
+        // Is this a FIN packet?
```
Comment (anandbonde) [inline src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs]: This comment can be removed as the next line is unambiguous.

File: src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs [hunk 4]
```diff
@@ -274,60 +186,166 @@ impl Receiver {
...
-            // We already owe our peer an ACK (the timer was already running), so cancel the timer and ACK now.
-            cb.receiver.ack_deadline_time_secs.set(None);
-            trace!("process_packet(): sending ack before deadline because another packet arrived");
-            Sender::send_ack(cb, layer3_endpoint);
+        Ok(())
+    }
+
+    pub fn get_receive_window_size(&self) -> u32 {
+        let bytes_unread: u32 = (self.receive_next_seq_no - self.reader_next_seq_no).into();
+        // The window should be less than 1GB or 64KB without scaling.
```
Comment (anandbonde) [inline src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs:270]: It would be good to not assume these absolute sizes in the comments. These are susceptible to going stale in case the values of constants change in future.

File: src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs [hunk 5]
```diff
@@ -274,60 +186,166 @@ impl Receiver {
...
+                if stored_entry.0 == self.receive_next_seq_no {
+                    // Move this entry's buffer from the out-of-order store to the receive queue.
+                    // This data is now considered to be "received" by TCP, and included in our RCV.NXT calculation.
+                    debug!("Recovering out-of-order packet at {}", self.receive_next_seq_no);
+                    if let Some(temp) = self.out_of_order_frames.pop_front() {
+                        self.receive_next_seq_no = self.receive_next_seq_no + SeqNumber::from(temp.1.len() as u32);
+                        // This inserts the segment and wakes a waiting pop coroutine.
+                        self.pop_queue.push(temp.1);
+                    }
+                } else {
```
Comment (anandbonde) [inline src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs]: This conditional can be inverted to reduce nesting. The indentation level is pretty high in this function. Along with that, it can be broken down into smaller functions if the indentation/nesting still remains high.

File: src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs (hunk 4 above)
Comment (iyzhang) [reply src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs:270]: Oh, these are TCP constants, so won't change unless something big changes in the RFC.

File: src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs (hunk 5 above)
Comment (iyzhang) [reply src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs]: Done! So much better!

File: src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs (hunk 2 above)
Comment (iyzhang) [reply src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs]: No, the data gets adjusted by the check_segment_in_window function. Given that each processing function might modify the buf, I thought doing a late binding was the best idea.

Comment (anandbonde) [reply src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs]: The whole body of `process_data_if_any` is wrapped in the `data.len() > 0` check. So it will be enough to just check for `has_data` before calling it instead. Also, this function is called just from here as of now.

**Review by anandbonde — APPROVED** [review]

File: src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs (hunk 2 above)
Comment (iyzhang) [reply src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs]: oh, I'm storing the data for later in the function below process_data which takes ownership of data, so I can't check it later.

Comment (anandbonde) [reply src/rust/inetstack/protocols/layer4/tcp/established/receiver.rs]: Thanks for changing. The code is more readable now.
