### PR TITLE
[inetstack] Bug Fix: Correct retransmission timer

### LINKED ISSUE #202: [inetstack] Retransmit Timer Issues
We should review the retransmit timer implementation, specifically for the following issues:

- The code seems overzealous about pushing the retransmit timer into the future.  One case in particular is in the retransmit function, where it resets the expiration deadline regardless of why retransmit was called (it can be called not only on timer expiration, but also because of Fast Retransmit -- where I believe the deadline should remain untouched).
- The timer appears to also be extended upon every arrival of a new ACK, is this really desired behavior?
- The timer doesn't record the sequence number it is tracking for retransmission, instead it does the above, which could make it wait longer than desired for retransmission.  Again, review that this is desired behavior.

### PR DESCRIPTION
**Pull request by iyzhang**
This PR closes #202. I have checked on all other cases and they seem to be correct. With this fix, we should be transmitting at the right times for retransmit.

### CODE REVIEW

File: src/rust/inetstack/protocols/layer4/tcp/established/sender.rs [hunk 1]
```diff
@@ -459,18 +459,23 @@ impl Sender {
...
-            } else {
-                // Update the retransmit timer.  Some of our outstanding data is now acknowledged, but not all.
-                // TODO: This looks wrong.  We should reset the retransmit timer to match the deadline for the
-                // oldest still-outstanding data.  The below is overly generous (minor efficiency issue).
-                let deadline: Instant = now + self.rto_calculator.rto();
-                self.retransmit_deadline_time_secs.set(Some(deadline));
-            }
+            // Reset the retransmit timer if necessary. If there is more data that hasn't been acked, then set to the
+            // next segment deadline, otherwise, do not set.
+            let retransmit_deadline_time_secs: Option<Instant> = match self.unacked_queue.get_front() {
```
Comment (anandbonde) [inline src/rust/inetstack/protocols/layer4/tcp/established/sender.rs]: The logic looks good. This is a good candidate for extracting into a separate function as it represents a nice logically independent block.

**Review by anandbonde — APPROVED** [review]
